// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  errorText: string;
  inputWrapper: string;
  label: string;
}
declare const cssExports: CssExports;
export default cssExports;
