// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  banner: string;
  container: string;
  'forgot-password': string;
  forgotPassword: string;
  'form-container': string;
  formContainer: string;
  header: string;
  headerLogo: string;
  mascot: string;
  'mascot-container': string;
  mascotContainer: string;
}
declare const cssExports: CssExports;
export default cssExports;
