// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  achievementIcon: string;
  achievementIconBg: string;
  achievementItem: string;
  achievementRow: string;
  achievementTitle: string;
  activeDot: string;
  activityContent: string;
  activityIcon: string;
  activityIconCircle: string;
  activityItem: string;
  activityList: string;
  activityMeta: string;
  activityTitle: string;
  avatarImage: string;
  avatarLarge: string;
  container: string;
  content: string;
  header: string;
  levelBadge: string;
  levelBadgeText: string;
  levelSub: string;
  levelTitle: string;
  profileEmail: string;
  profileName: string;
  progressBarBg: string;
  progressBarFill: string;
  progressCard: string;
  progressInfo: string;
  progressTop: string;
  sectionHeader: string;
  statsCard: string;
  statsGrid: string;
  statsIcon: string;
  statsIconRow: string;
  streakBadge: string;
  streakText: string;
}
declare const cssExports: CssExports;
export default cssExports;
