// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  badge: string;
  badgeText: string;
  cardContainer: string;
  contentWrapper: string;
  description: string;
  headerArea: string;
  iconCompleted: string;
  iconPending: string;
  metaRow: string;
  metaText: string;
  statusIconWrapper: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
