package com.example.sparkling.go.modules

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel


/**
 * GENERATED BY SPARKLING METHOD CLI.
 */

abstract class AbsPickFileMethodIDL : AbsSparklingIDLMethod<AbsPickFileMethodIDL.PickFileInputModel, AbsPickFileMethodIDL.PickFileResultModel>() {

    @IDLMethodName(name = "Filepicker.pickFile", params = ["type"], results = ["tempFiles"])
    final override val name: String = "Filepicker.pickFile"

    @IDLMethodParamModel
    interface PickFileInputModel : IDLMethodBaseParamModel {
        // This allows JS to pass ['*/*'] or specific types like ['image/*', 'application/pdf']
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "type", primitiveClassType = String::class)
        val type: List<String>
    }

    @IDLMethodResultModel
    interface PickFileResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "tempFiles", nestedClassType = BridgeBeanFileDetails::class)
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "tempFiles", nestedClassType = BridgeBeanFileDetails::class)
        var tempFiles: List<BridgeBeanFileDetails>?
    }

    interface BridgeBeanFileDetails : IDLMethodBaseModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "tempFilePath")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "tempFilePath")
        var tempFilePath: String?

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "name")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "name")
        var name: String?

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "size")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "size")
        var size: Number?
    }
}
