package com.example.sparkling.go.modules

import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel


/**
 * GENERATED BY SPARKLING METHOD CLI.
 */

abstract class AbsUploadFileMethodIDL : AbsSparklingIDLMethod<AbsUploadFileMethodIDL.UploadFileInputModel, AbsUploadFileMethodIDL.UploadFileResultModel>() {

    @IDLMethodName(name = "FileUploader.uploadFile", params = ["url", "answerText", "files"], results = ["responseBody"])
    final override val name: String = "FileUploader.uploadFile"

    @IDLMethodParamModel
    interface UploadFileInputModel : IDLMethodBaseParamModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "url", primitiveClassType = String::class)
        val url: String

        // optional — empty string for files-only submission
        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "answerText", primitiveClassType = String::class)
        val answerText: String?

        // optional — empty list for text-only submission
        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "files", nestedClassType = BridgeBeanUploadFile::class)
        val files: List<BridgeBeanUploadFile>?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "headers", primitiveClassType = String::class)
        val headers: Map<String, String>?
    }

    @IDLMethodResultModel
    interface UploadFileResultModel : IDLMethodBaseResultModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "responseBody", primitiveClassType = String::class)
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "responseBody", primitiveClassType = String::class)
        var responseBody: String?
    }

    interface BridgeBeanUploadFile : IDLMethodBaseModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "uri", primitiveClassType = String::class)
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "uri", primitiveClassType = String::class)
        var uri: String?

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "name", primitiveClassType = String::class)
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "name", primitiveClassType = String::class)
        var name: String?

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "mimeType", primitiveClassType = String::class)
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "mimeType", primitiveClassType = String::class)
        var mimeType: String?
    }
}
