// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  assignmentCard: string;
  blockWrapper: string;
  bottomSheet: string;
  buttonRow: string;
  caption: string;
  checkText: string;
  circleBtn: string;
  completedIcon: string;
  container: string;
  content: string;
  description: string;
  downloadBtn: string;
  downloadText: string;
  fileCard: string;
  fileInfo: string;
  fileName: string;
  fileSize: string;
  footerContainer: string;
  header: string;
  image: string;
  imageCard: string;
  itemActive: string;
  itemLocked: string;
  navbar: string;
  navbarProgress: string;
  primaryBtn: string;
  progressBarBg: string;
  progressBarFill: string;
  progressRow: string;
  progressText: string;
  quizInfo: string;
  radioActive: string;
  radioCircle: string;
  scrollView: string;
  sheetItem: string;
  sheetItemText: string;
  sheetList: string;
  sheetOpen: string;
  statusIconWrapper: string;
  textActive: string;
  textContent: string;
  uploadArea: string;
}
declare const cssExports: CssExports;
export default cssExports;
