// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  blockWrapper: string;
  caption: string;
  container: string;
  description: string;
  downloadBtn: string;
  downloadText: string;
  fileCard: string;
  fileInfo: string;
  fileName: string;
  fileSize: string;
  header: string;
  image: string;
  imageCard: string;
  scrollView: string;
  textContent: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
