// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actionBtn: string;
  actionBtnText: string;
  arrowIcon: string;
  arrowOpen: string;
  backButton: string;
  badge: string;
  badgeText: string;
  cardLabel: string;
  cardValue: string;
  checkCircle: string;
  checkCircleActive: string;
  container: string;
  contentBody: string;
  courseTitle: string;
  descriptionText: string;
  hero: string;
  iconBtn: string;
  lessonInfo: string;
  lessonItem: string;
  lessonList: string;
  lessonListVisible: string;
  lessonListWrapper: string;
  lessonMeta: string;
  lessonNumber: string;
  lessonTitle: string;
  lessonTitleLocked: string;
  lockIcon: string;
  locked: string;
  metaItem: string;
  metaRow: string;
  navRow: string;
  progressBarBg: string;
  progressBarFill: string;
  progressCard: string;
  progressTextRow: string;
  sectionTitle: string;
  unitContainer: string;
  unitHeader: string;
  unitItem: string;
  unitSubtitle: string;
  unitTitle: string;
  unitTitleSection: string;
}
declare const cssExports: CssExports;
export default cssExports;
