// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  achievementIcon: string;
  achievementItem: string;
  achievementLabel: string;
  achievementScroll: string;
  avatarContainer: string;
  avatarText: string;
  container: string;
  content: string;
  contentWrapper: string;
  courseCard: string;
  courseMeta: string;
  courseSubText: string;
  courseThumbnail: string;
  courseTitle: string;
  fireIcon: string;
  greetingText: string;
  header: string;
  headerContent: string;
  headerInfo: string;
  headerName: string;
  imageWrapper: string;
  'level-card': string;
  levelCard: string;
  levelCardInner: string;
  levelIcon: string;
  progressBarFill: string;
  progressBarTrack: string;
  recommendedCard: string;
  sectionHeaderRow: string;
  sectionTitle: string;
  seeAllLink: string;
  statsRow: string;
  streakBadge: string;
  streakText: string;
  tagText: string;
  userName: string;
  xpBadge: string;
  xpText: string;
}
declare const cssExports: CssExports;
export default cssExports;
