// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  body: string;
  dialog: string;
  mascot: string;
  'modal-body': string;
  modalBody: string;
  overlay: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
