// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  default: string;
  shimmerContainer: string;
  shimmerMove: string;
  shimmerWave: string;
}
declare const cssExports: CssExports;
export default cssExports;
