// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tiktok-ball': string;
  'tiktok-ball-left': string;
  'tiktok-ball-right': string;
  'tiktok-left': string;
  'tiktok-loader': string;
  'tiktok-right': string;
  tiktokBall: string;
  tiktokBallLeft: string;
  tiktokBallRight: string;
  tiktokLeft: string;
  tiktokLoader: string;
  tiktokRight: string;
}
declare const cssExports: CssExports;
export default cssExports;
