// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  scrollView: string;
  tabBar: string;
  tabIcon: string;
  tabIconActive: string;
  tabItem: string;
  tabItemActive: string;
  tabLabel: string;
  tabLabelActive: string;
}
declare const cssExports: CssExports;
export default cssExports;
