// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  avatarSvg: string;
  lbAvatar: string;
  lbAvatarText: string;
  lbAvatarWrapper: string;
  lbBadge: string;
  lbBadgeText: string;
  lbCard: string;
  lbCardFirst: string;
  lbCardHighlight: string;
  lbCardSecond: string;
  lbCardThird: string;
  lbInfo: string;
  lbName: string;
  lbRow: string;
  lbXp: string;
  xpIcon: string;
  xpRow: string;
}
declare const cssExports: CssExports;
export default cssExports;
