// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actionButton: string;
  actionIcon: string;
  actionMinus: string;
  avatarCircle: string;
  avatarSvg: string;
  avatarText: string;
  card: string;
  info: string;
  name: string;
  rankCircle: string;
  rankText: string;
  xpIcon: string;
  xpRow: string;
  xpText: string;
}
declare const cssExports: CssExports;
export default cssExports;
