package org.sparkling.filepicker.pickfile.Filepicker.pickFile

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel


/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
 
abstract class AbsPickFileMethodIDL : AbsSparklingIDLMethod<AbsPickFileMethodIDL.IDLMethodPickFileInputModel, AbsPickFileMethodIDL.IDLMethodPickFileResultModel>() {

    @IDLMethodName(name = "Filepicker.pickFile", params = ["type", "callback"], results = ["value"])
    final override val name: String = "Filepicker.pickFile"

    @IDLMethodParamModel
    interface IDLMethodPickFileInputModel : IDLMethodBaseParamModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "type", primitiveClassType = String::class)
        val type: List<String> 

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "callback")
        val callback: Unit? 
    }

    @IDLMethodResultModel
    interface IDLMethodPickFileResultModel: IDLMethodBaseResultModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "value")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "value")
        var value: Any? 
    }
}
