// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  categoryList: string;
  container: string;
  courseList: string;
  emptyState: string;
  emptyText: string;
  header: string;
  searchBar: string;
  searchIcon: string;
  searchInput: string;
}
declare const cssExports: CssExports;
export default cssExports;
