// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'course-thumbnail': string;
  courseThumbnail: string;
  'recommended-card': string;
  'recommended-tag': string;
  recommendedCard: string;
  recommendedTag: string;
  'title-name': string;
  'title-wrapper': string;
  titleName: string;
  titleWrapper: string;
}
declare const cssExports: CssExports;
export default cssExports;
