// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  backToLoginButton: string;
  container: string;
  description: string;
  emailText: string;
  footer: string;
  illustration: string;
  illustrationWrapper: string;
  instruction: string;
  resendBtnActive: string;
  resendBtnDisabled: string;
  resendTextActive: string;
  resendTextDisabled: string;
  timerText: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
